# Generated by Django 3.1.7 on 2021-03-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210305_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'get_latest_by': ['bids']},
        ),
    ]
