# Generated by Django 3.1.7 on 2021-03-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210305_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'get_latest_by': ['date']},
        ),
    ]
