# Generated by Django 3.1.7 on 2021-03-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='auctions.Comment'),
        ),
    ]
