# Generated by Django 3.1.7 on 2021-03-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210306_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(blank=True, choices=[('Books', 'Books'), ('Clothes', 'Clothes'), ('Toys', 'Toys'), ('Electronics', 'Electronics')], max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
